name: prebuild-node-addon
description: This action prebuilds the Node.js native addon, installs dependencies, builds the project, and uploads the resulting artifacts.
inputs:
  opencv-cmake-find-dir:
    description: 'Prebuild opencv artifact directory for cmake find'
    required: true
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version}}
        cache: pnpm
    - run: pnpm i
      shell: bash
    - run: pnpm build --CDOpenCV_DIR="${{ inputs.opencv-cmake-find-dir }}"
      shell: bash
    - run: pnpm test
      shell: bash
      env:
        ARTIFACT_NAME: addon-watermark-${{ runner.os }}-${{ runner.arch }}-${{ github.ref_name }}
        ARTIFACT_FILE_NAME: ${{ env.ARTIFACT_NAME }}.tar.gz
    - run: |
        rm -f ${{ env.ARTIFACT_FILE_NAME }}
        tar -cvzf ${{ env.ARTIFACT_FILE_NAME }} -C ./addon .
        echo "ADDON_ARTIFACT_NAME=${{ env.ARTIFACT_NAME }}" >> $GITHUB_OUTPUT
        echo "ADDON_ARTIFACT_FILE_NAME=${{ env.ARTIFACT_FILE_NAME }}" >> $GITHUB_OUTPUT
      shell: bash
      id: build-addon-artifact
    - name: Upload native addon artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.build-addon-artifact.outputs.ADDON_ARTIFACT_NAME }}
        path: ${{ steps.build-addon-artifact.outputs.ADDON_ARTIFACT_FILE_NAME }}
        if-no-files-found: error
        retention-days: 1
        overwrite: true