name: publish-to-npm-registry
description: Publishes the package to the NPM registry with the appropriate tag.
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        cache: pnpm

    - run: pnpm i
      shell: bash
      env:
        CI: true

    - name: Publish to NPM
      shell: bash
      run: |
        npm publish --access=public --provenance

        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "**Published:** $NEW_VERSION" >> $GITHUB_STEP_SUMMARY
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}